version: "3"

services:
  namenode:
    build: ./namenode    
    image: namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop-data/dfs/name
    environment:
      - CLUSTER_NAME=hadoop
    env_file:
      - ./hadoop.env

#   node:
#     build: ./node    
#     image: node
#     restart: always    
#     volumes:    
#       - hadoop_datanode:/hadoop-data/dfs/data
#     environment:
#       SERVICE_PRECONDITION: "namenode:9870 namenode:9000 resourcemanager:8088"
#       CONTAINER_NAME: "container1"
#     env_file:
#       - ./hadoop.env
  
#   node2:
#     build: ./node    
#     image: node
#     restart: always    
#     volumes:    
#       - hadoop_datanode:/hadoop-data/dfs/data
#     environment:
#       SERVICE_PRECONDITION: "namenode:9870 namenode:9000 resourcemanager:8088"
#       CONTAINER_NAME: "container3"
#     env_file:
#       - ./hadoop.env

#   node3:
#     build: ./node    
#     image: node
#     restart: always    
#     volumes:    
#       - hadoop_datanode:/hadoop-data/dfs/data
#     environment:
#       SERVICE_PRECONDITION: "namenode:9870 namenode:9000 resourcemanager:8088"
#       CONTAINER_NAME: "container2"
#     env_file:
#       - ./hadoop.env

#   resourcemanager:
#     build: ./resourcemanager    
#     image: resourcemanager
#     container_name: resourcemanager
#     restart: always
#     environment:
#       SERVICE_PRECONDITION: "namenode:9000 namenode:9870"
#     env_file:
#       - ./hadoop.env

  
#   historyserver:
#     build: ./historyserver   
#     image: historyserver 
#     container_name: historyserver
#     restart: always
#     environment:
#       SERVICE_PRECONDITION: "namenode:9000 namenode:9870 node:9864 resourcemanager:8088"
#     volumes:
#       - hadoop_historyserver:/hadoop/yarn/timeline
#     env_file:
#       - ./hadoop.env
  
volumes:
  hadoop_namenode:
  # hadoop_datanode:
  # hadoop_historyserver:
